import type { NextPage } from "next";
import Head from "next/head";
import Background from "../components/Background";
import Login from "../components/Login";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NEXUS GameStand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/crystal.png" />
      </Head>
      <main>
        <Background>
          <Login />
        </Background>
      </main>
    </>
  );
};

export default Home;
